### ISSUE TITLE
python setup.py error

### ISSUE THREAD

**Issue by scisco** [gipit/gippy#35]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gippy/__init__.py", line 23, in <module>
    from gippy import *
  File "gippy/gippy.py", line 30, in <module>
    _gippy = swig_import_helper()
  File "gippy/gippy.py", line 22, in swig_import_helper
    import _gippy
ImportError: No module named _gippy
```

**Comment by ircwaves** [comment]
Hello @scisco :
I've encountered an error like this when I've attempted to `import gippy` with my current working directory being the top level of my local repository.  Perhaps that's where you're importing?

**Comment by matthewhanson** [comment]
I think this is due to the way the mac install works (now on develop), which isn't fully correct.

When installing via 
pip install

it generates the error, but
pip develop
or
pip install -e

works when you import although it actually copies the binary .so files to site-packages, but also creates an egg-link back to the repo dir.   So it does work....

The install should work in all these cases:
- in virtual env and outside, where gippy including .so files are installed in dist-packages or site-packages
- in 'develop' mode, where it is installed via an egg-link back to the repo, or normal installation.

**Comment by matthewhanson** [comment]
All mac issues should now be fixed in develop.

the error can appear though as @ircwaves said, if you are in the repository that you just installed.  I run tests from within the tests directory to avoid that.
