### ISSUE TITLE
Numpy array to CImg conversion

### ISSUE THREAD

**Issue by matthewhanson** [gipit/gippy#4]
Assumes data types are the same, which is usually valid. However a user could pass in a numpy array to a function expecting a CImg of another type. GIPPY should automatically convert (just as it does when going CImg -> numpy)

**Comment by moloned** [comment]
Sorry for posting this here but I'm trying to wrap some existing C++ code based on Cimg for python3 and I get a runtime error when I try to pass a Cimg object to a C++ function via a boost:python wrapper 

>>> si = pyl.st_pipeline(img, bitPix, outerHfdDiameter)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
Boost.Python.ArgumentError: Python argument types in
    pywrap_startracker.st_pipeline(CImg, int, int)
did not match C++ signature:
    st_pipeline(cimg_library::CImg<float> img, long bitPix, int outerHfdDiameter)

I'm using pycimg

# test st_pipeline(img, bitPix, outerHfdDiameter)
#
from pycimg import CImg
import numpy as np
from astropy.io import fits
import numpy as np

fitsname = 'test.fits'
fits.info(fitsname)
image_data = fits.getdata(image_file, ext=0) # getdata returns 2D numpy array
img = CImg()
#img = image_data.astype(float)
img = CImg(image_data.astype(float)) # image_data is integer and pipeline requires floats
bitPix = 0 
outerHfdDiameter = 21
si = pyl.StarInfoT()
im = img.asarray()

The C++ function st_pipeline is called as:

StarInfoListT st_pipeline(CImg<float> img, long bitPix, int outerHfdDiameter) { 

Do you think this problem is related to pycimg?

Could I fix it by switching to gippy? (I've tried already but I'm on Ubuntu 20.04 and apt-cache is set to gdal 3.x which seems to break the gippy setup

Any recommendations would be welcome

FYI I also tried writing npy2cimg and cimg2npy functions which is what led me here initially
