### ISSUE TITLE
Add scale option to GoeImage.Save() 

### ISSUE THREAD

**Issue by scisco** [gipit/gippy#47]
Use case: convert UInt16 to UInt8

**Comment by matthewhanson** [comment]
As @scisco and I discussed, this will be a rescale function instead, that could be called before save, i.e.

geoimg.rescale(argshere).save(filename)

Because one might read the numpy array after rescaling, rather than saving to a new file.

rescale will not change datatype, it will simply do a linear scaling with some input limits (calculated form input image if not provided), and output limits.    To change the datatype, that will be a switch to save, making this similar to how one might do it in numpy (rescaling and change datatype are different operations)...

geoimg.rescale(argshere).read().astype('uint8')

With save:

geoimg.rescale(argshere).save(filename, dt='uint8')

But it up the user to scale the image to match the datatype if a datatype conversion is done.
