### ISSUE TITLE
Add warp option to GeoImage.Save()

### ISSUE THREAD

**Issue by scisco** [gipit/gippy#48]
Should accept any valid CRS string

**Comment by matthewhanson** [comment]
doing slight refactor of gippy warp implementation to make easier, will support changing projection as well as clipping by a geometry.

**Comment by matthewhanson** [comment]
slight refactor was larger refactor as it required a bunch of work on the geometry code.

warp is not an option to save, instead, warp is a separate function that will also save it, but reprojected. I think this is preferable because warping requires additional input parameters such as resolution and interpolation method.

geoimgout = geoimg.warp(filename, feature, crop, proj, xres, yres, interpolation)

- filename: of output
- feature: A GeoFeature instance*
- crop: if true, and a feature is given, the output will be cropped down to the intersection of the feature and the image.
- proj: any sort of string with proj info (eg "EPSG:4326" or a proj string, or even a filename with the proj info in it)
- xres/yres: the x and y resolution in same units as projection
- interpolation: interpolation method (0-nn, 1-bilinear, 2-cc)


Open any OGR source with GeoVector. This will have a number of features that can be indexed (ie vector[0] is the first feature).   The GeoFeature needs to have a projection set, in which case it will be used as the region of interest of the output (all values outside the feature will be set to nodata).

Note that warp will save a temporary image (which will be deleted after processing) before the reprojection, ensuring that any processing in the chain is performed before using GDAL to perform the warping.
